a=10
b=6
print("******Arithemetic operators****")
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**b)
print(a%b)
print(a//b)
print(pow(a,b))
print("*****Comparision operators*****")
print(a<b)
print(a>b)
print(a==b)
print(a!=b)
print(a<=b)
print(a>=b)
print("*****Logical operators******")
print(a and b)
print(not a)
print(a or b)
print("****BItWise operators****")
print(a & b)
print(a | b)
print(a^b)
print(~a)
print("***Shift operators****")
print(a<<b)
print(a>>b)